"""empty message

Revision ID: 237eb8cb7d07
Revises: 
Create Date: 2024-10-07 10:42:01.702681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237eb8cb7d07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('enclosure_id', sa.Integer(), nullable=False),
    sa.Column('food_type', sa.String(length=80), nullable=False),
    sa.Column('feeding_time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeding')
    # ### end Alembic commands ###
